version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    image: sophialj/awe-db:latest
    restart: always
    command: "/usr/sbin/sshd -D"
    env_file: dev.env
    ports:
      - "2223:22"
      - "8888:8000"
    volumes:
      - ./media-files:/media-files
      - ./static-files:/static-files
      - ./app:/app
      - ./scripts:/scripts
    depends_on:
      - postgres

volumes:
  postgres:
