# Generated by Django 2.0.3 on 2018-09-13 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWEClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='class name')),
                ('day', models.CharField(max_length=10, verbose_name='Day of the Week')),
                ('time', models.CharField(max_length=15)),
                ('total_classes', models.IntegerField(verbose_name='total classes')),
                ('program', models.CharField(choices=[('ESOL', 'ESOL'), ('EFES', 'EES'), ('PRES', 'Preschool'), ('PRIV', 'Private'), ('SPTH', 'Speech Therapy'), ('TUTR', 'Tutoring')], max_length=4, verbose_name='program')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='classroom')),
                ('location', models.CharField(choices=[('TH', 'Therwil'), ('RH', 'Riehen')], max_length=2, verbose_name='location')),
                ('spots', models.IntegerField(verbose_name='Spots')),
            ],
        ),
        migrations.CreateModel(
            name='FirstAid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.TextField()),
                ('start_date', models.DateField()),
                ('notes', models.TextField(max_length=500, verbose_name='data')),
                ('total_spot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_classes', models.IntegerField()),
                ('notes', models.TextField(blank=True, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='aweclass',
            name='books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awe_classes.Book'),
        ),
        migrations.AddField(
            model_name='aweclass',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awe_classes.Classroom', verbose_name='class room'),
        ),
        migrations.AddField(
            model_name='aweclass',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awe_classes.Session', verbose_name='Session'),
        ),
    ]
