# Generated by Django 2.0.3 on 2018-09-13 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awe_classes', '0002_aweclass_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aweclass',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='awe_classes.Book'),
        ),
    ]
