# Generated by Django 2.0.3 on 2018-09-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awe_classes', '0004_auto_20180913_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aweclass',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10, verbose_name='Day of the Week'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='location',
            field=models.CharField(choices=[('Therwil', 'Therwil'), ('Riehen', 'Riehen')], max_length=7, verbose_name='location'),
        ),
    ]
