# Generated by Django 2.0.3 on 2018-09-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awe_classes', '0005_auto_20180913_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aweclass',
            name='time',
        ),
        migrations.AddField(
            model_name='aweclass',
            name='end_time',
            field=models.TimeField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='aweclass',
            name='start_time',
            field=models.TimeField(blank=True, max_length=15, null=True),
        ),
    ]
