# Generated by Django 2.0.3 on 2018-09-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awe_classes', '0006_auto_20180913_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aweclass',
            name='end_time',
            field=models.TimeField(default='19:49:25', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aweclass',
            name='start_time',
            field=models.TimeField(default='19:49:25', max_length=15),
            preserve_default=False,
        ),
    ]
