name: app
channels:
- conda-forge
dependencies:
  - python=3.6
  - psycopg2=2.7.4
  - uwsgi=2.0.15
  - pip:
    - flake8==3.5.0
    - django==2.0.3
    - djangorestframework==3.8.2
    - djangorestframework-simplejwt==3.2.3
    - django-cors-headers==2.2.0
    - django-countries==5.2
    - django-admin-sortable2==0.6.19
