# Generated by Django 2.0.3 on 2018-09-13 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('awe_classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='street')),
                ('number', models.IntegerField(verbose_name='house number')),
                ('city', models.CharField(max_length=70, verbose_name='city')),
                ('zip', models.IntegerField(verbose_name='zip')),
                ('country', models.CharField(choices=[('SUI', 'Switzerland'), ('GER', 'Germany'), ('FRA', 'France')], max_length=3, verbose_name='country')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AD', 'Admin'), ('TE', 'teacher'), ('AS', 'assistant')], default='TE', max_length=50, verbose_name='role')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('birthdate', models.DateField(verbose_name='birthday')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.TextField(blank=True, max_length=12, null=True, verbose_name='phone number')),
                ('mobile', models.CharField(blank=True, max_length=12, null=True, verbose_name='mobile number')),
                ('contract', models.BooleanField(default=False, verbose_name='contract')),
                ('old_ahv', models.IntegerField(verbose_name='old ahv number')),
                ('ahv', models.IntegerField(verbose_name='ahv number')),
                ('profession', models.CharField(max_length=100, verbose_name='profession')),
                ('date_hired', models.DateField()),
                ('date_left', models.DateField(blank=True, null=True)),
                ('last_day', models.DateField()),
                ('start_salary', models.IntegerField()),
                ('salary_raise_date', models.DateField()),
                ('raise_step', models.IntegerField()),
                ('new_salary', models.IntegerField()),
                ('key', models.BooleanField(default=False)),
                ('swiss_permit', models.CharField(choices=[('CH', 'Swiss'), ('C', 'C-Permit'), ('B', 'B-Permit'), ('Other', 'Other'), ('None', 'None')], max_length=5)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Address', verbose_name='address')),
                ('first_aid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='awe_classes.FirstAid', verbose_name='first aid class')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('birthdate', models.DateField(verbose_name='birthday')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phones', models.TextField(max_length=12, verbose_name='phone numbers')),
                ('mother_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='mother name')),
                ('mother_workplace', models.CharField(blank=True, max_length=50, null=True, verbose_name='mother workplace')),
                ('father_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='father name')),
                ('father_workplace', models.CharField(blank=True, max_length=50, null=True, verbose_name='father workplace')),
                ('cambridge_exam', models.CharField(blank=True, max_length=100, null=True, verbose_name='cambridge exam')),
                ('registered', models.BooleanField(verbose_name='registered')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('cost_per_class', models.IntegerField(blank=True, null=True, verbose_name='cost per class')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='discount')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Address', verbose_name='address')),
                ('awe_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awe_classes.AWEClass', verbose_name='class')),
            ],
        ),
    ]
