# Generated by Django 2.0.3 on 2018-09-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='key',
        ),
        migrations.AddField(
            model_name='staff',
            name='key_riehen',
            field=models.BooleanField(default=False, verbose_name='Has key for Riehen?'),
        ),
        migrations.AddField(
            model_name='staff',
            name='key_therwil',
            field=models.BooleanField(default=False, verbose_name='Has key for Therwil?'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='new_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='raise_step',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('AD', 'admin'), ('TE', 'teacher'), ('AS', 'assistant')], default='TE', max_length=50, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary_raise_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='swiss_permit',
            field=models.CharField(choices=[('CH', 'Swiss Passport'), ('C', 'C-Permit'), ('B', 'B-Permit'), ('Other', 'Other'), ('None', 'None')], max_length=5),
        ),
    ]
