# Generated by Django 2.0.3 on 2018-09-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20180913_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='ahv',
            field=models.CharField(max_length=16, verbose_name='AHV Number'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='old_ahv',
            field=models.CharField(max_length=14, verbose_name='old AHV Number'),
        ),
    ]
