# Generated by Django 2.0.3 on 2018-09-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awe_classes', '0003_auto_20180913_1718'),
        ('people', '0004_auto_20180913_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='awe_class',
        ),
        migrations.AddField(
            model_name='student',
            name='awe_class',
            field=models.ManyToManyField(to='awe_classes.AWEClass', verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='discount',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='discount'),
        ),
    ]
