# Generated by Django 2.0.3 on 2018-09-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20180913_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phones',
            field=models.CharField(max_length=12, verbose_name='phone numbers'),
        ),
    ]
