# Generated by Django 2.0.3 on 2018-09-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20180913_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phones',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='phone numbers'),
        ),
    ]
