# Generated by Django 2.0.3 on 2018-09-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20180913_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='last_day',
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_hired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='old_ahv',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='old AHV Number'),
        ),
    ]
