# Generated by Django 2.0.3 on 2018-10-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20180916_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.TextField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=6, null=True),
        ),
    ]
