# Generated by Django 2.0.3 on 2018-10-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.TextField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
